# Generated by Django 4.1.2 on 2023-02-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Mobiles', 'Mobiles'), ('Camera', 'Camera'), ('Others', 'Others')], max_length=255),
        ),
    ]
